### ISSUE TITLE
Mongo object ID cast fail

### ISSUE THREAD

**Issue by neheren** [bitkompagniet/mugs#20]
When using admin@mugs.info (as authentication) to create user at `POST /` the following error presents itself:
<img width="964" alt="screen shot 2017-01-13 at 16 04 00" src="https://cloud.githubusercontent.com/assets/15888906/21936550/d0c1ac8e-d9b1-11e6-90c4-4963f588ac8c.png">
The user is added to the database.

**Comment by kparkov** [comment]
Fixed.
