### ISSUE TITLE
Change admin to write and member to read

### ISSUE THREAD

**Issue by kparkov** [bitkompagniet/mugs#37]
We want admin role to be called `write`, and member role to be called `read` in the future.

**Comment by kparkov** [comment]
I voted against doing this. Read and write are too broad, and will shadow any roles defined by other modules.

**Comment by neheren** [comment]
How about 'reader' and 'writer'? These are more role based terms.

**Comment by kparkov** [comment]
Still too broad. If, for example, a website module added a new role, "editor", it would suddenly be very unclear how this interacted with "writer". If anything, they should be renamed to "mugs-write" and "mugs-read". I just don't like that. :-D
