### ISSUE TITLE
Mail refactor

### ISSUE THREAD

**Issue by neheren** [bitkompagniet/mugs#45]
Add structure to the template object injection

**Comment by kparkov** [comment]
Is this still relevant, or was it fixed with the e-mail issues solved, @neheren?

**Comment by neheren** [comment]
It's WIP. I forgot to push [this commit](https://github.com/bitkompagniet/mugs/tree/issue/41/password-gen)

**Comment by kparkov** [comment]
Okay, so this might mean that #48 is already done.

**Comment by kparkov** [comment]
Let's review it together next time.

**Comment by kparkov** [comment]
We no longer know what this was really about. We are closing it.
