### ISSUE TITLE
Make it configurable whether unconfirmed logins should be allowed

### ISSUE THREAD

**Issue by kparkov** [bitkompagniet/mugs#72]
It should be configurable whether it is allowed to login when the user account is unconfirmed.

If it is not allowed, the login action should respond with a `403 Forbidden` when trying to authenticate. The error message should be reasonable.

**Comment by neheren** [comment]
What should the default value be?

**Comment by neheren** [comment]
Also I'm not sure how to unit test this, since some parts of the test does require unconfirmed logins. And the env variable is being set from test start.
